### ISSUE TITLE
对于组件的一些建议。

### ISSUE THREAD

**Issue by RSS1102** [janghood/shuimo-ui#23]
1. 按钮hover,click是否应该有不同的样式改变。
2. button,input,radio,checkbox 等禁用disabled 是否应该有不同颜色显示，以区别是否禁用or普通。
3. 普通select选择框，是否没必要有右侧的上下选择。
4. popover，是否应该背景不为透明色（或以不透明灰色，或添加选项等），以保证文字明确显示。
5. 抽屉drawer的关闭按钮是否应以弹窗dialog的关闭按钮一致（并在最右侧）。
6. 鼠标样式，是否也可为一组件（事件）。

**Comment by higuaifan** [comment]
**非常感谢你的建议**

### 按钮hover,click是否应该有不同的样式改变。

UI说该有，按钮组件很老了，一直没样式迭代，我们内部应用没有迭代需求，就一直放着了😂。

### button,input,radio,checkbox 等禁用disabled 是否应该有不同颜色显示，以区别是否禁用or普通。

UI也说该有，会改的。

### 普通select选择框，是否没必要有右侧的上下选择。

emmm这玩意是个Border引发的bug，近期内会修复。

### popover，是否应该背景不为透明色（或以不透明灰色，或添加选项等），以保证文字明确显示。

popover是一个非常古老的组件，以前是有单独应用场景的，样式一直没迭代，我们有计划将它替换掉。

### 抽屉drawer的关闭按钮是否应以弹窗dialog的关闭按钮一致（并在最右侧）。

drawer的关闭按钮是slot放进去的，并没有内置的，这两个组件我们会整理一下功能点并进行一些优化和统一，非常感谢这个建议。

### 鼠标样式，是否也可为一组件（事件）。

鼠标样式这个我们进行了一些考虑，在实际应用中感觉现在的方式是可控程度最高并且应用最简单的，如果你这边有什么好的设计建议的话可以讨论一下。

-----

再次感谢你的建议，近期内我们会进行一些修复更新，如果有兴趣的话也欢迎参与进来。

**Comment by RSS1102** [comment]
当然非常有兴趣参与到这个项目中来，也希望能从中学习到一些东西。
鼠标：希望ui效果可以被用户用到，可以传递受影响作用域（id）（或可选配置options在不同条件对应不同笔头颜色等）。
