### ISSUE TITLE
项目结构

### ISSUE THREAD

**Issue by ErKeLost** [janghood/shuimo-ui#35]
是否考虑monorepo组织结构

**Comment by higuaifan** [comment]
是指单个组件都`monorepo`吗？类似于`element`那种？

**Comment by RSS1102** [comment]
> 是否考虑monorepo组织结构

我理解的是：比如doc文档，一些脚本工具，或者一些其他辅助组件开发的功能在一个仓库内进行开发和维护？是这样嘛？

**Comment by ErKeLost** [comment]
类似 构建工具 组件库 文档 拆分细化一些

**Comment by ErKeLost** [comment]
> > 是否考虑monorepo组织结构
> 
> 我理解的是：比如doc文档，一些脚本工具，或者一些其他辅助组件开发的功能在一个仓库内进行开发和维护？是这样嘛？

是的

**Comment by higuaifan** [comment]
> 类似 构建工具 组件库 文档 拆分细化一些

`API`构建工具和`lint`工具有单独的库，这俩本身的场景也不是只用于`Shuimo-UI`库的，
文档本身已经拉出来有单独的库。

像`src`的那个确实可以拆分，以及部分构件模块可以拉出来，但本身项目除了组件库以外其他模块没啥内容，点感觉是为了`monorepo`而`monorepo`。
后续倒是有打算把核心的代码抽离出来，然后再做`monorepo`的打算，不过还在讨论和考虑中。。
除此之外你这边对`monorepo`的结构变动有什么好的建议吗？

**Comment by ErKeLost** [comment]
感觉这个库很有意思 想参与一下，个人感觉就类似 文档， playground， ui ， 可能后续还可能有根据组件库自己的构建cli 这种

**Comment by higuaifan** [comment]
> 感觉这个库很有意思 想参与一下，个人感觉就类似 文档， playground， ui ， 可能后续还可能有根据组件库自己的构建cli 这种

<img width="455" alt="image" src="https://user-images.githubusercontent.com/9988024/205053098-05910dbe-711c-4c67-aca7-a475e732b965.png">
🐶来群里细嗦？
